#!/usr/bin/python
# -*- coding: utf-8 -*-

country_names = {
'af':'Afghanistan ',
'ax':'Aland Islands ',
'al':'Albania ',
'dz':'Algeria ',
'as':'American Samoa ',
'ad':'Andorra ',
'ao':'Angola ',
'ai':'Anguilla ',
'aq':'Antarctica ',
'ag':'Antigua and Barbuda ',
'ar':'Argentina ',
'am':'Armenia ',
'aw':'Aruba ',
'ac':'Ascension Island ',
'au':'Australia ',
'at':'Austria ',
'az':'Azerbaijan ',
'bs':'Bahamas ',
'bh':'Bahrain ',
'bd':'Bangladesh ',
'bb':'Barbados ',
'by':'Belarus ',
'be':'Belgium ',
'bz':'Belize ',
'bj':'Benin ',
'bm':'Bermuda ',
'bt':'Bhutan ',
'bo':'Bolivia ',
'ba':'Bosnia and Herzegovina ',
'bw':'Botswana ',
'bv':'Bouvet Island ',
'br':'Brazil ',
'io':'British Indian Ocean Territory ',
'bn':'Brunei Darussalam ',
'bg':'Bulgaria ',
'bf':'Burkina Faso ',
'bi':'Burundi ',
'kh':'Cambodia ',
'cm':'Cameroon ',
'ca':'Canada ',
'cv':'Cap Verde ',
'ky':'Cayman Islands ',
'cf':'Central African Republic ',
'td':'Chad ',
'cl':'Chile ',
'cn':'China ',
'cx':'Christmas Island ',
'cc':'Cocos (Keeling) Islands ',
'co':'Colombia ',
'km':'Comoros ',
'cg':'Congo; Republic of ',
'cd':'Congo; The Democratic Republic of the ',
'ck':'Cook Islands ',
'cr':'Costa Rica ',
'ci':'Cote d''Ivoire ',
'hr':'Croatia/Hrvatska ',
'cu':'Cuba ',
'cy':'Cyprus ',
'cz':'Czech Republic ',
'dk':'Denmark ',
'dj':'Djibouti ',
'dm':'Dominica ',
'do':'Dominican Republic ',
'ec':'Ecuador ',
'eg':'Egypt ',
'sv':'El Salvador ',
'gq':'Equatorial Guinea ',
'er':'Eritrea ',
'ee':'Estonia ',
'et':'Ethiopia ',
'eu':'Euopean Union ',
'fk':'Falkland Islands (Malvina) ',
'fo':'Faroe Islands ',
'fj':'Fiji ',
'fi':'Finland ',
'fr':'France ',
'gf':'French Guiana ',
'pf':'French Polynesia ',
'tf':'French Southern Territories ',
'ga':'Gabon ',
'gm':'Gambia ',
'ge':'Georgia ',
'de':'Germany ',
'gh':'Ghana ',
'gi':'Gibraltar ',
'gr':'Greece ',
'gl':'Greenland ',
'gd':'Grenada ',
'gp':'Guadeloupe ',
'gu':'Guam ',
'gt':'Guatemala ',
'gg':'Guernsey ',
'gn':'Guinea ',
'gw':'Guinea-Bissau ',
'gy':'Guyana ',
'ht':'Haiti ',
'hm':'Heard and McDonald Islands ',
'va':'Holy See (City Vatican State) ',
'hn':'Honduras ',
'hk':'Hong Kong ',
'hu':'Hungary ',
'is':'Iceland ',
'in':'India ',
'id':'Indonesia ',
'ir':'Iran; Islamic Republic of ',
'iq':'Iraq ',
'ie':'Ireland ',
'im':'Isle of Man ',
'il':'Israel ',
'it':'Italy ',
'jm':'Jamaica ',
'jp':'Japan ',
'je':'Jersey ',
'jo':'Jordan ',
'kz':'Kazakhstan ',
'ke':'Kenya ',
'ki':'Kiribati ',
'kp':'Korea; Democratic Peoples Republic ',
'kr':'Korea; Republic of ',
'kw':'Kuwait ',
'kg':'Kyrgyzstan ',
'la':'Lao Peoples Democratic Republic ',
'lv':'Latvia ',
'lb':'Lebanon ',
'ls':'Lesotho ',
'lr':'Liberia ',
'ly':'Libyan Arab Jamahiriya ',
'li':'Liechtenstein ',
'lt':'Lithuania ',
'lu':'Luxembourg ',
'mo':'Macau ',
'mk':'Macedonia; The Former Yugoslav Republic of ',
'mg':'Madagascar ',
'mw':'Malawi ',
'my':'Malaysia ',
'mv':'Maldives ',
'ml':'Mali ',
'mt':'Malta ',
'mh':'Marshall Islands ',
'mq':'Martinique ',
'mr':'Mauritania ',
'mu':'Mauritius ',
'yt':'Mayotte ',
'mx':'Mexico ',
'fm':'Micronesia; Federal State of ',
'md':'Moldova; Republic of ',
'mc':'Monaco ',
'mn':'Mongolia ',
'me':'Montenegro ',
'ms':'Montserrat ',
'ma':'Morocco ',
'mz':'Mozambique ',
'mm':'Myanmar ',
'na':'Namibia ',
'nr':'Nauru ',
'np':'Nepal ',
'nl':'Netherlands ',
'an':'Netherlands Antilles ',
'nc':'New Caledonia ',
'nz':'New Zealand ',
'ni':'Nicaragua ',
'ne':'Niger ',
'ng':'Nigeria ',
'nu':'Niue ',
'nf':'Norfolk Island ',
'mp':'Northern Mariana Islands ',
'no':'Norway ',
'om':'Oman ',
'pk':'Pakistan ',
'pw':'Palau ',
'ps':'Palestinian Territories; Occupied ',
'pa':'Panama ',
'pg':'Papua New Guinea ',
'py':'Paraguay ',
'pe':'Peru ',
'ph':'Philippines ',
'pn':'Pitcairn Island ',
'pl':'Poland ',
'pt':'Portugal ',
'pr':'Puerto Rico ',
'qa':'Qatar ',
're':'Reunion Island ',
'ro':'Romania ',
'ru':'Russian Federation ',
'rw':'Rwanda ',
'sh':'Saint Helena ',
'kn':'Saint Kitts and Nevis ',
'lc':'Saint Lucia ',
'pm':'Saint Pierre and Miquelon ',
'vc':'Saint Vincent and the Grenadines ',
'ws':'Samoa ',
'sm':'San Marino ',
'st':'Sao Tome and Principe ',
'sa':'Saudi Arabia ',
'sn':'Senegal ',
'rs':'Serbia ',
'sc':'Seychelles ',
'sl':'Sierra Leone ',
'sg':'Singapore ',
'sk':'Slovak Republic ',
'si':'Slovenia ',
'sb':'Solomon Islands ',
'so':'Somalia ',
'za':'South Africa ',
'gs':'South Georgia and the South Sandwich Islands ',
'es':'Spain ',
'lk':'Sri Lanka ',
'sd':'Sudan ',
'sr':'Suriname ',
'sj':'Svalbard and Jan Mayen Islands ',
'sz':'Swaziland ',
'se':'Sweden ',
'ch':'Switzerland ',
'sy':'Syrian Arab Republic ',
'tw':'Taiwan ',
'tj':'Tajikistan ',
'tz':'Tanzania ',
'th':'Thailand ',
'tl':'Timor-Leste ',
'tg':'Togo ',
'tk':'Tokelau ',
'to':'Tonga ',
'tt':'Trinidad and Tobago ',
'tn':'Tunisia ',
'tr':'Turkey ',
'tm':'Turkmenistan ',
'tc':'Turks and Caicos Islands ',
'tv':'Tuvalu ',
'ug':'Uganda ',
'ua':'Ukraine ',
'ae':'United Arab Emirates ',
'gb':'United Kingdom ',
'us':'United States ',
'uy':'Uruguay ',
'um':'US Minor Outlying Islands ',
'uz':'Uzbekistan ',
'vu':'Vanuatu ',
've':'Venezuela ',
'vn':'Vietnam ',
'vg':'Virgin Islands (British) ',
'vi':'Virgin Islands (USA) ',
'wf':'Wallis and Futuna Islands ',
'eh':'Western Sahara ',
'ye':'Yemen ',
'yu':'Yugoslavia ',
'zm':'Zambia ',
'zw':'Zimbabwe ',
}
