#!/usr/bin/python
# -*- coding: utf-8 -*-

language_names = {
'ab':'Abkhazian ',
'aa':'Afar ',
'af':'Afrikaans ',
'ak':'Akan ',
'sq':'Albanian ',
'am':'Amharic ',
'ar':'Arabic ',
'an':'Aragonese ',
'hy':'Armenian ',
'as':'Assamese ',
'av':'Avaric ',
'ae':'Avestan ',
'ay':'Aymara ',
'az':'Azerbaijani ',
'bm':'Bambara ',
'ba':'Bashkir ',
'eu':'Basque ',
'be':'Belarusian ',
'bn':'Bengali ',
'bh':'Bihari ',
'bi':'Bislama ',
'nb':'Norwegian Bokmål ',
'bs':'Bosnian ',
'br':'Breton ',
'bg':'Bulgarian ',
'my':'Burmese ',
'ca':'Catalan, Valencian ',
'ch':'Chamorro ',
'ce':'Chechen ',
'ny':'Chichewa, Nyanja ',
'zh':'Chinese ',
'cu':'Church Slavonic',
'cv':'Chuvash ',
'kw':'Cornish ',
'co':'Corsican ',
'cr':'Cree ',
'hr':'Croatian ',
'cs':'Czech ',
'da':'Danish ',
'dv':'Divehi, Dhivehi, Maldivian ',
'nl':'Dutch, Flemish ',
'dz':'Dzongkha ',
'en':'English ',
'eo':'Esperanto ',
'et':'Estonian ',
'ee':'Ewe ',
'fo':'Faroese ',
'fj':'Fijian ',
'fi':'Finnish ',
'fr':'French ',
'ff':'Fulah ',
'gd':'Gaelic, Scottish Gaelic ',
'gl':'Galician ',
'lg':'Ganda ',
'ka':'Georgian ',
'de':'German ',
'el':'Greek',
'gn':'Guarani ',
'gu':'Gujarati ',
'ht':'Haitian, Haitian Creole ',
'ha':'Hausa ',
'he':'Hebrew ',
'hz':'Herero ',
'hi':'Hindi ',
'ho':'Hiri Motu ',
'hu':'Hungarian ',
'is':'Icelandic ',
'io':'Ido ',
'ig':'Igbo ',
'id':'Indonesian ',
'ia':'Interlingua',
'ie':'Interlingue ',
'iu':'Inuktitut ',
'ik':'Inupiaq ',
'ga':'Irish ',
'it':'Italian ',
'ja':'Japanese ',
'jv':'Javanese ',
'kl':'Kalaallisut, Greenlandic ',
'kn':'Kannada ',
'kr':'Kanuri ',
'ks':'Kashmiri ',
'kk':'Kazakh ',
'km':'Khmer ',
'ki':'Kikuyu, Gikuyu ',
'rw':'Kinyarwanda ',
'ky':'Kirghiz ',
'kv':'Komi ',
'kg':'Kongo ',
'ko':'Korean ',
'kj':'Kuanyama, Kwanyama ',
'ku':'Kurdish ',
'lo':'Lao ',
'la':'Latin ',
'lv':'Latvian ',
'li':'Limburgan, Limburger, Limburgish ',
'ln':'Lingala ',
'lt':'Lithuanian ',
'lu':'Luba-Katanga ',
'lb':'Luxembourgish, Letzeburgesch ',
'mk':'Macedonian ',
'mg':'Malagasy ',
'ms':'Malay ',
'ml':'Malayalam ',
'mt':'Maltese ',
'gv':'Manx ',
'mi':'Maori ',
'mr':'Marathi ',
'mh':'Marshallese ',
'mo':'Moldavian ',
'mn':'Mongolian ',
'na':'Nauru ',
'nv':'Navajo, Navaho ',
'nd':'Ndebele North ',
'nr':'Ndebele South',
'ng':'Ndonga ',
'ne':'Nepali ',
'se':'Northern Sami ',
'no':'Norwegian ',
'nn':'Norwegian Nynorsk, Nynorsk  ',
'oc':'Occitan, Provençal ',
'oj':'Ojibwa ',
'or':'Oriya ',
'om':'Oromo ',
'os':'Ossetian, Ossetic ',
'pi':'Pali ',
'pa':'Panjabi, Punjabi ',
'fa':'Persian ',
'pl':'Polish ',
'pt':'Portuguese ',
'ps':'Pushto ',
'qu':'Quechua ',
'rm':'Raeto-Romance ',
'ro':'Romanian ',
'rn':'Rundi ',
'ru':'Russian ',
'sm':'Samoan ',
'sg':'Sango ',
'sa':'Sanskrit ',
'sc':'Sardinian ',
'sr':'Serbian ',
'sn':'Shona ',
'ii':'Sichuan Yi ',
'sd':'Sindhi ',
'si':'Sinhala, Sinhalese ',
'sk':'Slovak ',
'sl':'Slovenian ',
'so':'Somali ',
'st':'Sotho, Southern ',
'es':'Spanish, Castilian ',
'su':'Sundanese ',
'sw':'Swahili ',
'ss':'Swati ',
'sv':'Swedish ',
'tl':'Tagalog ',
'ty':'Tahitian ',
'tg':'Tajik ',
'ta':'Tamil ',
'tt':'Tatar ',
'te':'Telugu ',
'-':'Tetum ',
'th':'Thai ',
'bo':'Tibetan ',
'ti':'Tigrinya ',
'to':'Tonga (Tonga Islands) ',
'ts':'Tsonga ',
'tn':'Tswana ',
'tr':'Turkish ',
'tk':'Turkmen ',
'tw':'Twi ',
'ug':'Uighur, Uyghur ',
'uk':'Ukrainian ',
'ur':'Urdu ',
'uz':'Uzbek ',
've':'Venda ',
'vi':'Vietnamese ',
'vo':'Volapük ',
'wa':'Walloon ',
'cy':'Welsh ',
'fy':'Western Frisian ',
'wo':'Wolof ',
'xh':'Xhosa ',
'yi':'Yiddish ',
'yo':'Yoruba ',
'za':'Zhuang, Chuang ',
'zu':'Zulu ',
}
