from django.db import models
from django.contrib.auth.models import User, UserManager
from django.utils.translation import ugettext_lazy as _
#from django.conf.global_settings import LANGUAGES
from country_names import country_names
from language_names import language_names
from django.forms import ModelForm

COUNTRIES = tuple(country_names.items())
LANGUAGES = tuple(language_names.items())

GENDER = (
    ('m', _('Male')),
    ('f', _('Female')),
)

class CustomUser(User):
    """User with custom settings."""
    country = models.CharField(_('Country'), default='xx', max_length=2, choices=COUNTRIES, help_text=_("Your country."))
    language = models.CharField(_('Language'), default='en', max_length=5, choices=LANGUAGES, help_text=_("Interface language."))
    gender = models.CharField(_('Gender'), blank=True, max_length=1, choices=GENDER, help_text=_("Enable gender search filter for others"))
    age = models.IntegerField(_('Age'), null=True, blank=True, help_text=_("Enable age search filter for others"))
    keywords = models.CharField(_('Keywords'), blank=True, max_length=120, help_text=_("Comma separated words, for others to search"))
    recipients = models.ManyToManyField('self', related_name='senders', symmetrical=False, null=True, blank=True)
    recipients_amount = models.IntegerField(_('Recipients amount'), default=3, help_text=_("Number of recipients for each message."))
    suggest_message = models.BooleanField(_('Suggest message'), default=False, help_text=_("Always use automatic message composition."))
    karma = models.IntegerField(_('Karma'), default=0)
    # Use UserManager to get the create_user method, etc.
    objects = UserManager()

    def __unicode__(self):
        return self.first_name + ' ' + self.last_name


    #username - Autogenerated, 30 Alphanumberic chars.
    #first_name - Optional. 30 characters or fewer.
    #last_name - Optional. 30 characters or fewer.
    #email - Optional. E-mail address.
    #password - IGNORE
    #is_staff - Boolean. Designates whether this user can access the admin site.
    #is_active - Boolean. Designates whether this user account should be considered active.
    #is_superuser - IGNORE
    #last_login - A datetime of the user's last login.
    #date_joined - A datetime designating when the account was created.

class PreferencesForm(ModelForm):
    class Meta:
        model = CustomUser
        exclude = ('username', 'password', 'is_staff', 'is_active', 'is_superuser', 'last_login', 'date_joined', 'groups', \
                   'user_permissions', 'recipients', 'karma')

